chroot_dir: '/var/bind9/chroot'
bind_user: 'bind'
bind_group: 'bind'
zone_default: {
    email: 'rumiles.googlemail.com',
    ttl: '604800',
    refresh: '12h',
    retry: '2h',
    expire: '2w',
    negative_cache_ttl: '1d',
    mail_text: 'v=spf1 a mx -all',
    nameserver: ['ns1.coders-of-the-caribbean.org','ns2.coders-of-the-caribbean.org'],
    nameserver_addresses: ['176.28.17.93', '195.201.139.126'],
    master_host: 'melee',
    master_address: '176.28.17.93'
    }
zones:
    - {
        serial: '2019031901',
        zone: 'coders-of-the-caribbean.org',
        mx: [{ priority: '10', host: 'mail'}],
        a: [
            {
                name:    ['coders-of-the-caribbean.org.','www','mail','melee','ns1'],
                address: ['176.28.17.93']
            },
            {
                name:    ['scabb','ns2'],
                address: ['195.201.139.126']
            }
            ]
    }
    - {
        serial: '2018120701',
        zone: 'coders-of-the-caribbean.de',
        mx: [{ priority: '10', host: 'mail'}],
        a: [
            {
                name:    ['coders-of-the-caribbean.de.','www','mail'],
                address: ['176.28.17.93']
            }
            ]
        }
    - {
        serial: '2019032501',
        zone: 'lauschwaren.de',
        master_host: 'scabb',
        master_address: '195.201.139.126',
        mx: [{ priority: '10', host: 'mail'}],
        a: [
            {
                name:    ['lauschwaren.de.','www','mail'],
                address: ['195.201.139.126']
            }
        cname: [
            {
                name: ["postfixadmin","spam"],
                link: "mail"
            },
            {
                name: ["webmail"],
                link: "www"
            }
            ]
    }

reverse_zones:
    - {
        serial: '2019010801',
        reverse_zone: '176.28.17.93',
        ptr: ['coders-of-the-caribbean.org.','mail.coders-of-the-caribbean.org.','coders-of-the-caribbean.de.','mail.coders-of-the-caribbean.de.']
    }
    - {
        serial: '2019010801',
        reverse_zone: '195.201.139.126',
        master_host: 'scabb',
        master_address: '195.201.139.126',
        ptr: ['lauschwaren.de.','mail.lauschwaren.de.']
    }
