---

  - name: "Add worpress installation"
    docker_service:
      project_name: "Wordpress"
      definition:
        wordpress:
          image: wordpress
          links:
          - db:mysql
          ports:
          - 8080:80

        db:
          image: mariadb
          environment:
            MYSQL_ROOT_PASSWORD: example
