---

- name: Create whoami base dir
  file:
    state: directory
    path: "{{ whoami_base_dir }}"
    owner: "{{ ansible_user }}"
    group: docker
    mode: 0755

- name: Copy over docker-compose.yaml
  template:
    src: 'docker-compose.yaml'
    dest: "{{ whoami_base_dir }}/docker-compose.yaml"
    owner: "{{ ansible_user }}"
    group: docker
    mode: 0644


