---

- set_fact:
    zone_filepath: "{{ chroot_dir }}/etc/bind/{{ zone_filename }}"

- include: retrieve_next_serial.yaml

- name: Create DKIM key
  block:
  - file:
      state: directory
      mode: '700'
      path: "{{ dkim_dir }}"
      owner: "{{ ansible_user }}"
      group: docker
      recurse: yes
  - pip:
      name: pyOpenSSL
      state: present
  - openssl_privatekey:
      path: "{{ dkim_dir }}/{{ item.zone }}.private.key"
      owner: "{{ ansible_user }}"
      group: docker
      size: 1024
  - openssl_publickey:
      path: "{{ dkim_dir }}/{{ item.zone }}.public.key"
      privatekey_path: "{{ dkim_dir }}/{{ item.zone }}.private.key"
      owner: "{{ ansible_user }}"
      group: docker
  when: item.mx is defined

- name: Create zone file
  template:
    src: "{{ zone_template }}"
    dest: "{{ zone_filepath }}"
    owner: root
    group: "{{ bind_group }}"
    mode: 0644
