---

- set_fact:
    zone_filepath: "{{ chroot_dir }}/etc/bind/{{ zone_filename }}"

- include: retrieve_next_serial.yaml

- name: Create DKIM key
  block:
  - file:
      state: directory
      mode: '700'
      path: "{{ dkim_dir }}/{{ item.zone }}"
      owner: "{{ ansible_user }}"
      group: docker
      recurse: yes
  - pip:
      name: pyOpenSSL
      state: present
  - set_fact:
      dkim_private_key_file: "{{ dkim_dir }}/{{ item.zone }}/private.key"
      dkim_public_key_file: "{{ dkim_dir }}/{{ item.zone }}/public.key"
  - openssl_privatekey:
      path: "{{ dkim_private_key_file }}"
      owner: "{{ ansible_user }}"
      group: docker
      size: 1024
  - openssl_publickey:
      path: "{{ dkim_public_key_file }}"
      privatekey_path: "{{ dkim_private_key_file }}"
      owner: "{{ ansible_user }}"
      group: docker
  - slurp:
      src: "{{ dkim_public_key_file }}"
    register: dkim_public_key_content
  - set_fact:
      dkim_public_key: "{{ dkim_public_key_content['content'] | b64decode | replace('\n','') | replace('-----BEGIN PUBLIC KEY-----','') | replace('-----END PUBLIC KEY-----','') }}"
  when: item.mx is defined

- name: Create zone file
  template:
    src: "{{ zone_template }}"
    dest: "{{ zone_filepath }}"
    owner: root
    group: "{{ bind_group }}"
    mode: 0644
