---

  - name: Install bind DNS package
    apt: name='bind9' state=present

  - name: Create directories for chroot environment
    file:
      state: directory
      mode: '755'
      path: "{{ chroot_dir }}{{ item }}"
    with_items:
      - '/etc/bind'
      - '/dev'
      - '/var/cache/bind'
      - '/var/run/named'

  - name: Create directory for backup zone files written by bind daemon
    file:
      state: directory
      mode: '755'
      owner: "{{ bind_user }}"
      group: "{{ bind_group }}"
      path:  "{{ chroot_dir }}/var/lib/bind"

  - name: create devices in chroot environment
    shell: mknod -m 0666 "{{ chroot_dir }}{{ item.localdev }}" c 1 {{ item.localvalue }}
    args:
      creates: "{{ chroot_dir }}{{ item.localdev }}"
    with_items:
      - { localdev: '/dev/null',    localvalue: '3'}
      - { localdev: '/dev/random',  localvalue: '8'}

  - name: copy system files
    shell: "cp {{ item }} {{ chroot_dir }}{{ item }}"
    args:
      creates: "{{ chroot_dir }}{{ item }}"
    with_items:
      - '/etc/localtime'

  - name: configure rsyslogd
    template:
      src: rsyslog.conf.j2
      dest: /etc/rsyslog.d/22-bind-chroot.conf
      mode: 0644
    register: rsyslogconf

  - name: restart rsyslogd
    systemd:
      name: rsyslog
      state: restarted
    when: rsyslogconf.changed

  - name: create rndc configuration
    shell: "rndc-confgen -a -t {{ chroot_dir }}"
    args:
      creates: "{{ chroot_dir }}/etc/bind/rndc.key"

  - name: set permissions for rndc.key
    file:
      path: "{{ chroot_dir }}/etc/bind/rndc.key"
      owner: "{{ bind_user }}"
      group: "{{ bind_group }}"
      mode: 0640

  - name: copy simple configuration files
    copy:
      src: "{{ item }}"
      dest: "{{ chroot_dir }}/etc/bind/{{ item }}"
      owner: root
      group: "{{ bind_group }}"
      mode: 0644
    with_items:
      - 'bind.keys'
      - 'db.0'
      - 'db.127'
      - 'db.255'
      - 'db.empty'
      - 'db.local'
      - 'db.root'
      - 'named.conf'
      - 'named.conf.default-zones'
      - 'zones.rfc1918'

  - name: configure options file
    template:
      src: named.conf.options.j2
      dest: "{{ chroot_dir }}/etc/bind/named.conf.options"
      owner: root
      group: "{{ bind_group }}"
      mode: 0644

  - name: configure local zone files
    template:
      src: named.conf.local.j2
      dest: "{{ chroot_dir }}/etc/bind/named.conf.local"
      owner: root
      group: "{{ bind_group }}"
      mode: 0644

  - name: configure forward zone files
    template:
      src: db.zone.j2
      dest: "{{ chroot_dir }}/etc/bind/db.{{ item.zone }}"
      owner: root
      group: "{{ bind_group }}"
      mode: 0644
    when: (item.master_host is defined and item.master_host == inventory_hostname) or
           zone_default.master_host == inventory_hostname
    with_items:
      "{{ zones }}"

  - name: configure reverse zone files
    template:
      src: db.reverse_zone.j2
      dest: "{{ chroot_dir }}/etc/bind/db.{{ item.reverse_zone[item.reverse_zone.rfind('.')+1:] }}"
      owner: root
      group: "{{ bind_group }}"
      mode: 0644
    when: (item.master_host is defined and item.master_host == inventory_hostname) or
          zone_default.master_host == inventory_hostname
    with_items:
      "{{ reverse_zones }}"

  - name: Configure firewall for DNS
    ufw: rule=allow port=53 proto={{ item }}
    with_items:
      - 'tcp'
      - 'udp'

  - name: Prepare systemd configuration directories
    file:
      state: directory
      owner: root
      group: root
      mode: 0755
      path: /etc/systemd/system/bind9.service.d


  - name: Configure systemd to start bind with chroot
    template:
      src: chroot.conf.j2
      dest: /etc/systemd/system/bind9.service.d/chroot.conf
      owner: root
      group: root
      mode: 0644

  - name: Don't start the service yet
    systemd:
      daemon_reload: yes
      name: bind9
      state: stopped
      enabled: no
