---

- name: Configure firewall for mail
  ufw: rule=allow port={{item}} proto='tcp'
  loop:
  - 25
  - 465
  - 4190

- name: Create mail base dir
  file:
    state: directory
    path: "{{ mail_base_dir }}"
    owner: "{{ ansible_user }}"
    group: docker
    mode: 0755

- name: Copy over docker-compose.yaml
  template:
    src: 'docker-compose.yaml'
    dest: "{{ mail_base_dir }}/docker-compose.yaml"
    owner: "{{ ansible_user }}"
    group: docker
    mode: 0644

- name: Enable mail.service
  systemd:
    name: docker-compose@mail.service
    state: stopped #restarted
    enabled: false #true
    daemon_reload: yes