---
  - include_tasks: "{{ ansible_os_family }}.yaml"

  - name: Provide ssh access config for backup user
    template:
      src: 'config'
      dest: "~/.ssh/config"
      mode: 0644
    become: false
