---

- name: Install basic packages
  apt: name={{packages}} state=present update_cache=yes
  vars:
    packages:
    - python3-setuptools
    - python3-venv
    - python3-pip
    - vim
    - zsh
    - tmux
    - exa
    - bat
    - ripgrep
    - fzf
    - zoxide
    - mc
    - rmlint
    - ncdu
    - btop
    - neovim

