---

# https://docs.docker.com/engine/installation/linux/docker-ce/debian/
- name: remove any old docker versions (and docker-compose binary)
  apt: name={{packages}} state=absent purge=yes
  vars:
    packages:
    - docker
    - docker-engine
    - docker.io
    - docker-compose
    - containerd
    - runc

- name: Install prerequisites for https repository
  apt: name={{packages}} state=present update_cache=yes
  vars:
    packages:
    - apt-transport-https
    - ca-certificates
    - curl
    - gnupg2
    - lsb-release
    - software-properties-common

- name: Add Key for docker repo
  apt_key:
    url: 'https://download.docker.com/linux/debian/gpg'
    id: 0EBFCD88
    state: present

- name: Add official docker repository
  apt_repository:
    repo: deb [arch=amd64] https://download.docker.com/linux/debian {{ ansible_lsb.codename }} stable
    filename: docker.list
    state: present

- name: Install docker-ce
  apt: name={{packages}} state=present update_cache=yes
  vars:
    packages:
    - 'docker-ce'
    - 'docker-ce-cli'
    - 'containerd.io'

