---
  - name: Retrieve get docker script
    get_url: url=https://get.docker.com dest=/tmp/get_docker.sh mode=0744
 
  - name: Run get docker script
    shell: /tmp/get_docker.sh

  - name: Install docker
    apt: name=docker-engine update-cache=yes
 
  - name: get setuptools
    apt: name=python-setuptools state=present
 
  - name: make sure pip works
    shell: easy_install -U pip creates=/usr/local/bin/pip
 
  - name: install docker-py
    pip: name=docker-py state=present
 
  - name: install docker-compose
    pip: name=docker-compose state=present