---
- include: "{{ ansible_os_family }}.yaml"

- name: Ensure old module not present
  pip:
    name: docker-py
    state: absent

- name: Install pip modules on target box
  pip:
    name: "{{ packages }}"
    state: present
  vars:
    packages:
    - docker
    - docker-compose==1.15.0

- name: Add user to docker group
  user:
    name: "{{ ansible_user }}"
    groups: docker

- name: Add docker base directory
  file:
    state: directory
    mode: '755'
    owner: "{{ ansible_user }}"
    group: docker
    path: "{{ docker_base_dir }}"

- name: New systemd service to run docker-compose
  template:
    src: docker-compose.service
    dest: /etc/systemd/system/docker-compose@.service

- name: Add ipv6 to daemon.json
  copy:
    src: daemon.json
    dest: /etc/docker/daemon.json
