version: "3.7"
networks:
  default:
    external: true
    name: "{{ traefik_network }}"

services:
  traefik:
    image: traefik:v2.3
    container_name: traefik
    restart: unless-stopped
    ports:
     - 80:80
     - 443:443
    command:
      - --providers.docker=true
      - --providers.docker.exposedbydefault=false
    volumes:
     - /var/run/docker.sock:/var/run/docker.sock:rw
     - ./static.yaml:/etc/traefik/traefik.yaml
     - ./dynamic.yaml:/etc/traefik/dynamic/dynamic.yaml
     - "{{ letsencrypt_dir }}/acme.json:/etc/traefik/acme/acme.json"
