version: '3.8'

networks:
  default:
    external: true
    name: "{{ traefik_network }}"

services:
  mail-certdumper:
    image: ghcr.io/kereis/traefik-certs-dumper:latest
    volumes:
      - "{{ letsencrypt_dir }}:/traefik:ro"
      - ./mail_letsencrypt:/output:rw
    environment:
      - DOMAIN="mail.{{ mailserver_domains[inventory_hostname] }}"


  mailserver:
    image: ghcr.io/docker-mailserver/docker-mailserver:latest
    container_name: mailserver
    hostname: mail
    domainname: "{{ mailserver_domains[inventory_hostname] }}"
    ports:
      - "25:25"       # SMTP
      - "143:143"     # IMAP
      - "587:587"     # SMTPS
      - "993:993"     # IMAPS
      - "4190:4190"   # SIEVE
    volumes:
      - ./docker-data/dms/mail-data/:/var/mail/
      - ./docker-data/dms/mail-state/:/var/mail-state/
      - ./docker-data/dms/mail-logs/:/var/log/mail/
      - ./docker-data/dms/config/:/tmp/docker-mailserver/
      - ./mail_letsencrypt/:/etc/letsencrypt/
      - /etc/localtime:/etc/localtime:ro
    environment:
      ENABLE_FAIL2BAN: 1
      
      # Using letsencrypt for SSL/TLS certificates
      SSL_TYPE: letsencrypt
      SSL_DOMAIN: "mail.{{ mailserver_domains[inventory_hostname] }}"
      
      # Disallow sending emails from other docker containers without authentication
      # When changing beware creating an Open Relay: https://docker-mailserver.github.io/docker-mailserver/edge/config/environment/#permit_docker
      PERMIT_DOCKER: none
      
      # All env below are default settings:
      ONE_DIR: 1
      ENABLE_POSTGREY: 0
      ENABLE_CLAMAV: 0
      ENABLE_SPAMASSASSIN: 0
      
      # You may want to enable this: https://docker-mailserver.github.io/docker-mailserver/edge/config/environment/#spoof_protection
      # See step 8 below, which demonstrates setup with enabled/disabled SPOOF_PROTECTION:
      SPOOF_PROTECTION: 0
    cap_add:
      - NET_ADMIN # For Fail2Ban to work
