version: '3.8'

networks:
  default:
    external: true
    name: "{{ traefik_network }}"

services:
  # mail-certdumper:
  #   image: ghcr.io/kereis/traefik-certs-dumper:latest
  #   volumes:
  #     - "{{ letsencrypt_dir }}:/traefik:ro"
  #     - ./mail_letsencrypt:/output:rw
  #   environment:
  #     - DOMAIN="mail.{{ mailserver_domains[inventory_hostname] }}"

  # mailserver-traefik:
  #   image: registry.gitlab.com/youtous/docker-mailserver-traefik:latest
  #   container_name: mailserver-traefik
  #   volumes:
  #     - /var/run/docker.sock:/var/run/docker.sock
  #     - "{{ letsencrypt_dir }}/acme.json:/tmp/traefik/acme.json:ro" # link traefik acme.json file (read-only)
  #   environment:
  #     - TRAEFIK_VERSION=2
  #     - CERTS_SOURCE=file
  #     - DOMAINS="mail.{{ mailserver_domains[inventory_hostname] }}"
  #     - PUSH_PERIOD=1m


  mailserver:
    image: ghcr.io/docker-mailserver/docker-mailserver:latest
    container_name: mailserver
    # command: > # Since v10.3.0, certificates must be present at startup: https://github.com/docker-mailserver/docker-mailserver/blob/a4095a7d48082fe0dbfd2146cf9be4ed743736d1/target/scripts/startup/setup-stack.sh#L989
    #   sh -c '
    #     mkdir -p $$(dirname "$$SSL_KEY_PATH") &&
    #     touch -a "$$SSL_KEY_PATH" &&
    #     touch -a "$$SSL_CERT_PATH" &&
    #     supervisord -c /etc/supervisor/supervisord.conf
    #   '
    hostname: mail
    domainname: "{{ mailserver_domains[inventory_hostname] }}"
    ports:
      - "25:25"       # SMTP
      - "143:143"     # IMAP
      - "587:587"     # SMTPS
      - "993:993"     # IMAPS
      - "4190:4190"   # SIEVE
    volumes:
      - "./docker-data/dms/mail-data/:/var/mail/"
      - "./docker-data/dms/mail-state/:/var/mail-state/"
      - "./docker-data/dms/mail-logs/:/var/log/mail/"
      - "./docker-data/dms/config/:/tmp/docker-mailserver/"
      - "{{ letsencrypt_dir }}/acme.json:/etc/letsencrypt/acme.json:ro"
      - "/etc/localtime:/etc/localtime:ro"
    labels:
      # - "mailserver-traefik.renew.domain=mail.{{ mailserver_domains[inventory_hostname] }}" # tag the service 

      - "traefik.enable=true" # use traefik v2 for certificate generation
      - "traefik.port=443" # dummy port, required generating certs with traefik
      - "traefik.http.routers.mail.tls=true"
      - "traefik.http.routers.mail.tls.certresolver=default"
      - "traefik.http.routers.mail.rule=Host(`mail.{{ mailserver_domains[inventory_hostname] }}`)" 
      - "traefik.http.routers.mail.entrypoints=websecure"
      - "traefik.http.routers.mail.middlewares=redirect-webmail@docker" # redirect to webmail
      - "traefik.http.middlewares.redirect-webmail.redirectregex.regex=.*"
      - "traefik.http.middlewares.redirect-webmail.redirectregex.replacement=https://{{ mailserver_domains[inventory_hostname] }}/"

    environment:
      # Using letsencrypt for SSL/TLS certificates
      - SSL_TYPE=letsencrypt
      - SSL_DOMAIN="mail.{{ mailserver_domains[inventory_hostname] }}"
      # - SSL_CERT_PATH=/var/mail-state/manual-ssl/cert
      # - SSL_KEY_PATH=/var/mail-state/manual-ssl/key

      - ENABLE_FAIL2BAN=1
      
      # Disallow sending emails from other docker containers without authentication
      # When changing beware creating an Open Relay: https://docker-mailserver.github.io/docker-mailserver/edge/config/environment/#permit_docker
      - PERMIT_DOCKER=none
      
      # All env below are default settings:
      - ONE_DIR=1
      - ENABLE_POSTGREY=0
      - ENABLE_CLAMAV=0
      - ENABLE_SPAMASSASSIN=0
      
      # You may want to enable this: https://docker-mailserver.github.io/docker-mailserver/edge/config/environment/#spoof_protection
      # See step 8 below, which demonstrates setup with enabled/disabled SPOOF_PROTECTION:
      - SPOOF_PROTECTION=0
    cap_add:
      - NET_ADMIN # For Fail2Ban to work
