version: "3.7"
networks:
  default:
    external: true
    name: "{{ traefik_network }}"

services:
  web2:
    image: containous/whoami
    labels:
     - "traefik.http.routers.web2.rule=Host(`{{ host_info[ inventory_hostname ].hostname }}`)"
     - "traefik.http.routers.web2.tls.certResolver=default"
     - "traefik.http.routers.web2.tls=true"
